### ISSUE TITLE
Make the License explicit

### ISSUE THREAD

**Issue by mahata** [kanakogi/WP-Theme-Test#3]
In your `readme.txt`, it says that the license is GPL 2.0 (or later). However, there's no description about it in your `README.md` so it might be a bit tough to figure out if it's worth cloning at a glance.

I'd suggest making a file named `LICENSE` or add the same description to `README.md` as well :smiley:

**Comment by mahata** [comment]
Please feel free to close it if you think it's trivial :smile:

**Comment by kanakogi** [comment]
I changed README.mb. How is it?

**Comment by mahata** [comment]
Awesome! Looks good to me :+1:

**Comment by kanakogi** [comment]
Thank you for your suggestion.
